@startuml Bank Standart Context

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Person(Client, "Client", "Client of Standart")

Enterprise_Boundary(BankStandart, "Standart Bank") {
    System(Website, "Bank Standart Web site", " Web site")
    System(InternetBank, "Internet Bank Standart", "Internet Bank")
    System(ABS, "ABS", "ABS")
    System(CallCenterSystem, "Call-Center System", "Call-Center System")
}

System_Ext(SmsGateway, "SMS Gateway", "")
System_Ext(CallCenter, "Call-center", "")
System_Ext(PartnerCallCenter, "Partner Call-center", "")
System_Ext(BackOffice, "Back Office", "")

Rel(Client, Website, "Request")
Rel(Client, InternetBank, "Online-request")

Rel(Website, CallCenterSystem, "REST API")
Rel(CallCenterSystem, CallCenter, "")
Rel(CallCenterSystem, PartnerCallCenter, "")

Rel(InternetBank, ABS, "Kafka")
Rel(InternetBank, SmsGateway, "SMS")
Rel(ABS, BackOffice, "Agreement of conditions")
Rel(ABS, SmsGateway, "Asserts")

@enduml